language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - pytest tests

notifications:
  email: false
  slack: prevlab:duJn4BAET8sPRW9wpKVpnY97
  